// Teste da API REST

@baseURL = https://projeto-backend-gti.herokuapp.com
@id = 6154dde3a246fc44bf87b6a4

###
// GET - Listar todos os planetas
GET {{baseURL}}/planetas
Content-Type: application/json

###
// GET - Listar um planeta pelo id
GET {{baseURL}}/planetas/{{id}}
Content-Type: application/json

###
// DELETE - Apaga um planeta pelo id
DELETE {{baseURL}}/planetas/{{id}}
Content-Type: application/json

###
// POST - Incluir um novo planeta
POST {{baseURL}}/planetas
Content-Type: application/json

{
    "nome": "Júpiter",
    "raioKM": "69911",
    "numSatelites": "79",
    "distanceSolUA": "5.2",
    "tipo": "gasoso"
}

###
// PUT - Altera um planeta já existente
PUT {{baseURL}}/planetas
Content-Type: application/json

{
    "_id": "615cd20a465b37bc89274705",
    "nome": "Júpiter",
    "raioKM": "69911",
    "numSatelites": "79",
    "distanceSolUA": "5.2",
    "tipo": "gasoso"
}