// Teste da API REST

@baseURL = https://projeto-backend-gti.herokuapp.com
@id = 

###
// GET - Listar todos os planetas
GET {{baseURL}}/planetas
Content-Type: application/json

###
// GET - Listar um planeta pelo id
GET {{baseURL}}/planetas/{{id}}
Content-Type: application/json

###
// DELETE - Apaga um planeta pelo id
DELETE {{baseURL}}/planetas/{{id}}
Content-Type: application/json

###
// POST - Incluir um novo planeta
POST {{baseURL}}/planetas
Content-Type: application/json

{
    "nome": "Vênus",
    "raioKM": "6051",
    "numSatelites": "0",
    "distanceSolUA": "0.72",
    "tipo": "rochoso"
}

###
// PUT - Altera um planeta já existente
PUT {{baseURL}}/planetas
Content-Type: application/json

{
    "_id": "",
    "nome": "Urano",
    "raioKM": "25362",
    "numSatelites": "27",
    "distanceSolUA": "19.2",
    "tipo": "gasoso"
}